import * as z from "zod";

export const menagesSchema = z.object({
  email: z.string().email().optional().or(z.literal("")),
  nom_repondant: z.string().min(1, "Le nom du répondant est requis"),
  nb_personnes_foyer: z.coerce.number().min(1).optional(),
  type_habitation: z.string().optional(),
  commune: z.string().optional(),
  quartier: z.string().optional(),
  reperes_visuels: z.string().optional(),
  accessibilite: z.string().optional(),
  mode_evacuation: z.string().optional(),
  motif_non_abonne: z.string().optional(),
  nom_pme_connue: z.string().optional(),
  libre_choix_collecteur: z.string().optional(),
  a_change_collecteur: z.string().optional(),
  motifs_insatisfaction: z.array(z.string()).optional(),
  nb_sacs_semaine: z.coerce.number().optional(),
  typologie_dechets: z.array(z.string()).optional(),
  alerte_ramassage_actuelle: z.string().optional(),
  bacs_debordants_7_jours: z.string().optional(),
  interet_bouton_commande: z.string().optional(),
  respect_horaire: z.string().optional(),
  notification_approche: z.string().optional(),
  suivi_carte_temps_reel: z.string().optional(),
  preuve_passage: z.string().optional(),
  procedure_absence: z.string().optional(),
  tri_actuel: z.string().optional(),
  facteurs_stimulants: z.array(z.string()).optional(),
  connaissance_risques: z.array(z.string()).optional(),
  pret_modules_video: z.string().optional(),
  montant_mensuel_gnf: z.coerce.number().optional(),
  perception_qualite_prix: z.string().optional(),
  mode_paiement: z.string().optional(),
  recu_papier: z.string().optional(),
  conflit_paiement: z.string().optional(),
  nature_differend: z.string().optional(),
  resolution_litige: z.string().optional(),
  possession_smartphone: z.string().optional(),
  frequence_mobile_money: z.string().optional(),
  applications_favorites: z.string().optional(),
  pret_installer_labal: z.string().optional(),
  telephone_groupe_test: z.string().optional(),
  suggestions_amelioration: z.string().optional(),
});

export type MenagesFormData = z.infer<typeof menagesSchema>;
