import { z } from "zod";

export const transitSchema = z.object({
  email_responsable: z.string().email("Email invalide").optional().or(z.literal("")),
  nom_site: z.string().min(1, "Le nom du site est requis"),
  statut_site: z.string().min(1, "Le statut est requis"),
  entite_gestionnaire: z.string().min(1, "L'entité gestionnaire est requise"),
  commune: z.string().min(1, "La commune est requise"),
  quartier_repere: z.string().optional(),
  capacite_caissons: z.coerce.number().optional(),
  cloture_dalle: z.enum(["true", "false"]).optional(),
  equipements: z.array(z.string()).default([]),
  presence_pont_bascule: z.enum(["true", "false"]).optional(),
  tri_sur_place: z.enum(["true", "false"]).optional(),
  filieres_triees: z.array(z.string()).default([]),
  nb_trieurs: z.coerce.number().optional(),
  acheteurs: z.string().optional(),
  nb_pme_clientes: z.coerce.number().optional(),
  nb_rotations_quotidiennes: z.coerce.number().optional(),
  tranches_horaires_pointe: z.string().optional(),
  acces_limite_agrees: z.enum(["true", "false"]).optional(),
  redevance_deversement: z.enum(["true", "false"]).optional(),
  refus_acces: z.enum(["true", "false"]).optional(),
  causes_refus: z.array(z.string()).default([]),
  outil_enregistrement: z.string().optional(),
  donnees_consignees: z.array(z.string()).default([]),
  frequence_rotation: z.string().optional(),
  prestataire_transporteur: z.string().optional(),
  frequence_saturation: z.string().optional(),
  consequences_environnementales: z.string().optional(),
  causes_blocage: z.array(z.string()).default([]),
  duree_max_blocage: z.string().optional(),
  canal_alerte_mairie: z.string().optional(),
  delai_reaction_communal: z.string().optional(),
  encaissements_especes_vs_mobile: z.string().optional(),
  litiges_caisse: z.enum(["true", "false"]).optional(),
  dotation_epi: z.array(z.string()).default([]),
  nuisances_vecteurs: z.string().optional(),
  local_securise_courant: z.enum(["true", "false"]).optional(),
  qualite_reseau_4g: z.string().optional(),
  smartphone_fonction: z.enum(["true", "false"]).optional(),
  bouton_alerte_sos: z.enum(["true", "false"]).optional(),
  suivi_gps_camions: z.enum(["true", "false"]).optional(),
  contact_responsable: z.string().optional(),
  suggestions_amenagement: z.string().optional(),
});

export type TransitFormData = z.infer<typeof transitSchema>;
